# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reference.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from GUI.pictures import resources

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 650)
        Dialog.setMinimumSize(QtCore.QSize(1000, 650))
        Dialog.setMaximumSize(QtCore.QSize(1000, 650))
        Dialog.setStyleSheet("background-color: transparent;\n"
"")
        self.BackgroundFrame = QtWidgets.QFrame(Dialog)
        self.BackgroundFrame.setGeometry(QtCore.QRect(0, -10, 1050, 700))
        self.BackgroundFrame.setMinimumSize(QtCore.QSize(1050, 700))
        self.BackgroundFrame.setMaximumSize(QtCore.QSize(1050, 700))
        self.BackgroundFrame.setStyleSheet("background-image: url(:/backgrounds/backgrounds/Reference.png);")
        self.BackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundFrame.setObjectName("BackgroundFrame")
        self.ExitButton = QtWidgets.QPushButton(Dialog)
        self.ExitButton.setGeometry(QtCore.QRect(970, 0, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(31, 37, 51, 10);\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    color: rgb(199, 199, 199);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgba(194, 194, 194, 50);\n"
"    color: rgb(255, 60, 63)\n"
"    }")
        self.ExitButton.setObjectName("ExitButton")
        self.ReferenceButton = QtWidgets.QPushButton(Dialog)
        self.ReferenceButton.setGeometry(QtCore.QRect(10, 0, 21, 21))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ReferenceButton.setFont(font)
        self.ReferenceButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(31, 37, 51, 0);\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    color: rgb(199, 199, 199);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgba(194, 194, 194, 50);\n"
"    color: #5abe41\n"
"    }")
        self.ReferenceButton.setObjectName("ReferenceButton")
        self.ReferenceLabel = QtWidgets.QLabel(Dialog)
        self.ReferenceLabel.setGeometry(QtCore.QRect(50, 40, 231, 41))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.ReferenceLabel.setFont(font)
        self.ReferenceLabel.setStyleSheet("background-color: none;\n"
"color: #ffffff;")
        self.ReferenceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ReferenceLabel.setObjectName("ReferenceLabel")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 90, 981, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scrollArea.setStyleSheet("QScrollBar:vertical{\n"
"    background: transparent;\n"
"    width: 5px;\n"
"    margin: 0;\n"
"    }\n"
"QScrollBar::handle:vertical{\n"
"    background-color: #5abe41;\n"
"    min-height: 20px;\n"
"    }\n"
"QScrollBar::add-line:vertical{\n"
"    background: transparent;\n"
"    height: 0px;\n"
"    }\n"
"QScrollBar::sub-line:vertical{\n"
"    background: transparent;\n"
"    height: 0px;\n"
"    }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: transparent;\n"
"    height: 0px;\n"
"    }")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1456, 976, 2681))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 150, -1, 150)
        self.verticalLayout_3.setSpacing(40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.OriginalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(12)
        self.OriginalLabel.setFont(font)
        self.OriginalLabel.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OriginalLabel.setObjectName("OriginalLabel")
        self.verticalLayout_3.addWidget(self.OriginalLabel)
        self.OriginalLabel_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(12)
        self.OriginalLabel_3.setFont(font)
        self.OriginalLabel_3.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.OriginalLabel_3.setObjectName("OriginalLabel_3")
        self.verticalLayout_3.addWidget(self.OriginalLabel_3)
        self.OriginalLabel_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_6.setFont(font)
        self.OriginalLabel_6.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_6.setObjectName("OriginalLabel_6")
        self.verticalLayout_3.addWidget(self.OriginalLabel_6)
        self.TranslateString = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString.setFont(font)
        self.TranslateString.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString.setReadOnly(True)
        self.TranslateString.setObjectName("TranslateString")
        self.verticalLayout_3.addWidget(self.TranslateString)
        self.OriginalLabel_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_5.setFont(font)
        self.OriginalLabel_5.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_5.setObjectName("OriginalLabel_5")
        self.verticalLayout_3.addWidget(self.OriginalLabel_5)
        self.TranslateString_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_2.setFont(font)
        self.TranslateString_2.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_2.setReadOnly(True)
        self.TranslateString_2.setObjectName("TranslateString_2")
        self.verticalLayout_3.addWidget(self.TranslateString_2)
        self.OriginalLabel_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_9.setFont(font)
        self.OriginalLabel_9.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_9.setObjectName("OriginalLabel_9")
        self.verticalLayout_3.addWidget(self.OriginalLabel_9)
        self.OriginalLabel_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_10.setFont(font)
        self.OriginalLabel_10.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_10.setObjectName("OriginalLabel_10")
        self.verticalLayout_3.addWidget(self.OriginalLabel_10)
        self.TranslateString_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_3.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_3.setFont(font)
        self.TranslateString_3.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_3.setReadOnly(True)
        self.TranslateString_3.setObjectName("TranslateString_3")
        self.verticalLayout_3.addWidget(self.TranslateString_3)
        self.OriginalLabel_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(12)
        self.OriginalLabel_4.setFont(font)
        self.OriginalLabel_4.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.OriginalLabel_4.setObjectName("OriginalLabel_4")
        self.verticalLayout_3.addWidget(self.OriginalLabel_4)
        self.TranslateString_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_4.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_4.setFont(font)
        self.TranslateString_4.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_4.setReadOnly(True)
        self.TranslateString_4.setObjectName("TranslateString_4")
        self.verticalLayout_3.addWidget(self.TranslateString_4)
        self.OriginalLabel_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_11.setFont(font)
        self.OriginalLabel_11.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_11.setObjectName("OriginalLabel_11")
        self.verticalLayout_3.addWidget(self.OriginalLabel_11)
        self.TranslateString_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_5.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_5.setFont(font)
        self.TranslateString_5.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_5.setReadOnly(True)
        self.TranslateString_5.setObjectName("TranslateString_5")
        self.verticalLayout_3.addWidget(self.TranslateString_5)
        self.OriginalLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(12)
        self.OriginalLabel_2.setFont(font)
        self.OriginalLabel_2.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.OriginalLabel_2.setObjectName("OriginalLabel_2")
        self.verticalLayout_3.addWidget(self.OriginalLabel_2)
        self.TranslateString_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_6.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_6.setFont(font)
        self.TranslateString_6.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_6.setReadOnly(True)
        self.TranslateString_6.setObjectName("TranslateString_6")
        self.verticalLayout_3.addWidget(self.TranslateString_6)
        self.OriginalLabel_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_12.setFont(font)
        self.OriginalLabel_12.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_12.setObjectName("OriginalLabel_12")
        self.verticalLayout_3.addWidget(self.OriginalLabel_12)
        self.TranslateString_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_7.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_7.setFont(font)
        self.TranslateString_7.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_7.setReadOnly(True)
        self.TranslateString_7.setObjectName("TranslateString_7")
        self.verticalLayout_3.addWidget(self.TranslateString_7)
        self.OriginalLabel_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(12)
        self.OriginalLabel_7.setFont(font)
        self.OriginalLabel_7.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.OriginalLabel_7.setObjectName("OriginalLabel_7")
        self.verticalLayout_3.addWidget(self.OriginalLabel_7)
        self.TranslateString_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_8.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_8.setFont(font)
        self.TranslateString_8.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_8.setReadOnly(True)
        self.TranslateString_8.setObjectName("TranslateString_8")
        self.verticalLayout_3.addWidget(self.TranslateString_8)
        self.OriginalLabel_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_13.setFont(font)
        self.OriginalLabel_13.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_13.setObjectName("OriginalLabel_13")
        self.verticalLayout_3.addWidget(self.OriginalLabel_13)
        self.TranslateString_9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_9.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_9.setFont(font)
        self.TranslateString_9.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_9.setReadOnly(True)
        self.TranslateString_9.setObjectName("TranslateString_9")
        self.verticalLayout_3.addWidget(self.TranslateString_9)
        self.OriginalLabel_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_8.setFont(font)
        self.OriginalLabel_8.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.OriginalLabel_8.setObjectName("OriginalLabel_8")
        self.verticalLayout_3.addWidget(self.OriginalLabel_8)
        self.TranslateString_10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_10.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_10.setFont(font)
        self.TranslateString_10.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_10.setReadOnly(True)
        self.TranslateString_10.setObjectName("TranslateString_10")
        self.verticalLayout_3.addWidget(self.TranslateString_10)
        self.OriginalLabel_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.OriginalLabel_14.setFont(font)
        self.OriginalLabel_14.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"")
        self.OriginalLabel_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OriginalLabel_14.setObjectName("OriginalLabel_14")
        self.verticalLayout_3.addWidget(self.OriginalLabel_14)
        self.TranslateString_11 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TranslateString_11.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(9)
        self.TranslateString_11.setFont(font)
        self.TranslateString_11.setStyleSheet("QTextEdit{\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    color: #ffffff;\n"
"    }\n"
"QTextEdit:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    border-radius: 15px;\n"
"    }\n"
"")
        self.TranslateString_11.setReadOnly(True)
        self.TranslateString_11.setObjectName("TranslateString_11")
        self.verticalLayout_3.addWidget(self.TranslateString_11)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.SearchLine = QtWidgets.QLineEdit(Dialog)
        self.SearchLine.setGeometry(QtCore.QRect(380, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        self.SearchLine.setFont(font)
        self.SearchLine.setStyleSheet("QLineEdit{\n"
"    background-color: #5abe41;\n"
"    border: 2px solid #5abe41;\n"
"    border-radius: 15px;\n"
"    color: #1f2533;\n"
"    }\n"
"QLineEdit:hover{\n"
"    background-color: #438e30;\n"
"    border: #438e30;\n"
"    color: #ffffff;\n"
"    }")
        self.SearchLine.setAlignment(QtCore.Qt.AlignCenter)
        self.SearchLine.setReadOnly(False)
        self.SearchLine.setObjectName("SearchLine")
        self.AboutToolButton = QtWidgets.QPushButton(Dialog)
        self.AboutToolButton.setGeometry(QtCore.QRect(770, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.AboutToolButton.setFont(font)
        self.AboutToolButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(31, 37, 51, 50);\n"
"    border: 2px solid #ffffff;\n"
"    border-radius: 20px;\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgba(194, 194, 194, 50);\n"
"    border: #c2c2c2;\n"
"    }")
        self.AboutToolButton.setObjectName("AboutToolButton")
        self.WindowMoveButton = QtWidgets.QPushButton(Dialog)
        self.WindowMoveButton.setGeometry(QtCore.QRect(0, 0, 1001, 21))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.WindowMoveButton.setFont(font)
        self.WindowMoveButton.setStyleSheet("QPushButton{\n"
"    color: transparent;\n"
"}")
        self.WindowMoveButton.setObjectName("WindowMoveButton")
        self.BottomShadowFrame = QtWidgets.QFrame(Dialog)
        self.BottomShadowFrame.setGeometry(QtCore.QRect(-50, 610, 1100, 80))
        self.BottomShadowFrame.setMinimumSize(QtCore.QSize(1100, 80))
        self.BottomShadowFrame.setMaximumSize(QtCore.QSize(1100, 200))
        self.BottomShadowFrame.setMouseTracking(False)
        self.BottomShadowFrame.setAcceptDrops(False)
        self.BottomShadowFrame.setStyleSheet("image: url(:/effects/effects/large_bottom_shadow.png);")
        self.BottomShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomShadowFrame.setObjectName("BottomShadowFrame")
        self.BackgroundFrame.raise_()
        self.WindowMoveButton.raise_()
        self.scrollArea.raise_()
        self.ReferenceButton.raise_()
        self.ExitButton.raise_()
        self.ReferenceLabel.raise_()
        self.SearchLine.raise_()
        self.AboutToolButton.raise_()
        self.BottomShadowFrame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ExitButton.setText(_translate("Dialog", "X"))
        self.ReferenceButton.setText(_translate("Dialog", "?"))
        self.ReferenceLabel.setText(_translate("Dialog", "Справка"))
        self.OriginalLabel.setText(_translate("Dialog", "Процесс локализации модификаций"))
        self.OriginalLabel_3.setText(_translate("Dialog", "1. Модификация"))
        self.OriginalLabel_6.setText(_translate("Dialog", "1.1. Вручную"))
        self.TranslateString.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Следует отметить, что внедрение современных методик предопределяет высокую востребованность системы массового участия. Предварительные выводы неутешительны: современная методология разработки обеспечивает широкому кругу (специалистов) участие в формировании укрепления моральных ценностей. Следует отметить, что понимание сути ресурсосберегающих технологий создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса первоочередных требований.</p></body></html>"))
        self.OriginalLabel_5.setText(_translate("Dialog", "1.2. SteamWorkshop ID"))
        self.TranslateString_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Следует отметить, что внедрение современных методик предопределяет высокую востребованность системы массового участия. Предварительные выводы неутешительны: современная методология разработки обеспечивает широкому кругу (специалистов) участие в формировании укрепления моральных ценностей. Следует отметить, что понимание сути ресурсосберегающих технологий создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса первоочередных требований.</p></body></html>"))
        self.OriginalLabel_9.setText(_translate("Dialog", "1.3. Коллекция (Смотри пункт 2.)"))
        self.OriginalLabel_10.setText(_translate("Dialog", "Возможные ошибки"))
        self.TranslateString_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Пока что ошибок не обнаружено.</p></body></html>"))
        self.OriginalLabel_4.setText(_translate("Dialog", "2. Коллекция"))
        self.TranslateString_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Следует отметить, что внедрение современных методик предопределяет высокую востребованность системы массового участия. Предварительные выводы неутешительны: современная методология разработки обеспечивает широкому кругу (специалистов) участие в формировании укрепления моральных ценностей. Следует отметить, что понимание сути ресурсосберегающих технологий создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса первоочередных требований.</p></body></html>"))
        self.OriginalLabel_11.setText(_translate("Dialog", "Возможные ошибки"))
        self.TranslateString_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Пока что ошибок не обнаружено.</p></body></html>"))
        self.OriginalLabel_2.setText(_translate("Dialog", "3. Язык интерфейса"))
        self.TranslateString_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Следует отметить, что внедрение современных методик предопределяет высокую востребованность системы массового участия. Предварительные выводы неутешительны: современная методология разработки обеспечивает широкому кругу (специалистов) участие в формировании укрепления моральных ценностей. Следует отметить, что понимание сути ресурсосберегающих технологий создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса первоочередных требований.</p></body></html>"))
        self.OriginalLabel_12.setText(_translate("Dialog", "Возможные ошибки"))
        self.TranslateString_7.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Пока что ошибок не обнаружено.</p></body></html>"))
        self.OriginalLabel_7.setText(_translate("Dialog", "4. Язык перевода"))
        self.TranslateString_8.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Следует отметить, что внедрение современных методик предопределяет высокую востребованность системы массового участия. Предварительные выводы неутешительны: современная методология разработки обеспечивает широкому кругу (специалистов) участие в формировании укрепления моральных ценностей. Следует отметить, что понимание сути ресурсосберегающих технологий создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса первоочередных требований.</p></body></html>"))
        self.OriginalLabel_13.setText(_translate("Dialog", "Возможные ошибки"))
        self.TranslateString_9.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Пока что ошибок не обнаружено.</p></body></html>"))
        self.OriginalLabel_8.setText(_translate("Dialog", "5. Расширенный сортировщик модов"))
        self.TranslateString_10.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Следует отметить, что внедрение современных методик предопределяет высокую востребованность системы массового участия. Предварительные выводы неутешительны: современная методология разработки обеспечивает широкому кругу (специалистов) участие в формировании укрепления моральных ценностей. Следует отметить, что понимание сути ресурсосберегающих технологий создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса первоочередных требований.</p></body></html>"))
        self.OriginalLabel_14.setText(_translate("Dialog", "Возможные ошибки"))
        self.TranslateString_11.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KB Astrolyte\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Пока что ошибок не обнаружено.</p></body></html>"))
        self.SearchLine.setText(_translate("Dialog", "Поиск"))
        self.AboutToolButton.setText(_translate("Dialog", "Об утилите"))
        self.WindowMoveButton.setText(_translate("Dialog", "Steam"))
