# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateTranslation.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from GUI.pictures import resources

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 380)
        Dialog.setMinimumSize(QtCore.QSize(650, 380))
        Dialog.setMaximumSize(QtCore.QSize(650, 380))
        Dialog.setStyleSheet("background-color: transparent;\n"
"")
        self.BackgroundFrame = QtWidgets.QFrame(Dialog)
        self.BackgroundFrame.setGeometry(QtCore.QRect(0, -10, 687, 387))
        self.BackgroundFrame.setMinimumSize(QtCore.QSize(687, 387))
        self.BackgroundFrame.setMaximumSize(QtCore.QSize(687, 387))
        self.BackgroundFrame.setStyleSheet("background-image: url(:/backgrounds/backgrounds/UpdateTranslation.png);")
        self.BackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundFrame.setObjectName("BackgroundFrame")
        self.ExitButton = QtWidgets.QPushButton(Dialog)
        self.ExitButton.setGeometry(QtCore.QRect(620, 0, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(31, 37, 51, 10);\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    color: rgb(199, 199, 199);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgba(194, 194, 194, 50);\n"
"    color: rgb(255, 60, 63)\n"
"    }")
        self.ExitButton.setText("X")
        self.ExitButton.setObjectName("ExitButton")
        self.ReferenceButton = QtWidgets.QPushButton(Dialog)
        self.ReferenceButton.setGeometry(QtCore.QRect(10, 0, 21, 21))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ReferenceButton.setFont(font)
        self.ReferenceButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(31, 37, 51, 0);\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgba(56, 57, 61, 50);\n"
"    color: rgb(199, 199, 199);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgba(194, 194, 194, 50);\n"
"    color: #5abe41\n"
"    }")
        self.ReferenceButton.setText("?")
        self.ReferenceButton.setObjectName("ReferenceButton")
        self.UpdateTranslationLabel = QtWidgets.QLabel(Dialog)
        self.UpdateTranslationLabel.setGeometry(QtCore.QRect(20, 40, 281, 41))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateTranslationLabel.setFont(font)
        self.UpdateTranslationLabel.setStyleSheet("background-color: none;\n"
"color: #ffffff;")
        self.UpdateTranslationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateTranslationLabel.setObjectName("UpdateTranslationLabel")
        self.BottomShadowFrame = QtWidgets.QFrame(Dialog)
        self.BottomShadowFrame.setGeometry(QtCore.QRect(-20, 300, 687, 100))
        self.BottomShadowFrame.setMinimumSize(QtCore.QSize(687, 100))
        self.BottomShadowFrame.setMaximumSize(QtCore.QSize(687, 100))
        self.BottomShadowFrame.setMouseTracking(False)
        self.BottomShadowFrame.setAcceptDrops(False)
        self.BottomShadowFrame.setStyleSheet("background-image: url(:/effects/effects/bottom_shadow.png);")
        self.BottomShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomShadowFrame.setObjectName("BottomShadowFrame")
        self.WindowMoveButton = QtWidgets.QPushButton(Dialog)
        self.WindowMoveButton.setGeometry(QtCore.QRect(0, 0, 651, 21))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.WindowMoveButton.setFont(font)
        self.WindowMoveButton.setStyleSheet("QPushButton{\n"
"    color: transparent;\n"
"}")
        self.WindowMoveButton.setText("")
        self.WindowMoveButton.setObjectName("WindowMoveButton")
        self.MainTitleLabel = QtWidgets.QLabel(Dialog)
        self.MainTitleLabel.setGeometry(QtCore.QRect(10, 101, 281, 31))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MainTitleLabel.setFont(font)
        self.MainTitleLabel.setStyleSheet("background-color: none;\n"
"color: #ffffff;")
        self.MainTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MainTitleLabel.setObjectName("MainTitleLabel")
        self.NewTitleLabel = QtWidgets.QLabel(Dialog)
        self.NewTitleLabel.setGeometry(QtCore.QRect(360, 100, 271, 31))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.NewTitleLabel.setFont(font)
        self.NewTitleLabel.setStyleSheet("background-color: none;\n"
"color: #ffffff;")
        self.NewTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NewTitleLabel.setObjectName("NewTitleLabel")
        self.ChooseNewFileButton = QtWidgets.QPushButton(Dialog)
        self.ChooseNewFileButton.setGeometry(QtCore.QRect(430, 156, 141, 27))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ChooseNewFileButton.setFont(font)
        self.ChooseNewFileButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(50, 50, 50, 50);\n"
"    border: #c2c2c2;\n"
"    border-radius: 13px;\n"
"    min-height: 27px;\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: #31858f;\n"
"    border: #31858f;\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: #05B8CC;\n"
"    border: 2px solid #05B8CC;\n"
"    }")
        self.ChooseNewFileButton.setObjectName("ChooseNewFileButton")
        self.ChooseMainFileButton = QtWidgets.QPushButton(Dialog)
        self.ChooseMainFileButton.setGeometry(QtCore.QRect(80, 154, 141, 27))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ChooseMainFileButton.setFont(font)
        self.ChooseMainFileButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(50, 50, 50, 50);\n"
"    border: #c2c2c2;\n"
"    border-radius: 13px;\n"
"    min-height: 27px;\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: #438e30;\n"
"    border: #31858f;\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: #c2c2c2;\n"
"    border: 2px solid #c2c2c2;\n"
"    }")
        self.ChooseMainFileButton.setObjectName("ChooseMainFileButton")
        self.MainStatusLabel = QtWidgets.QLabel(Dialog)
        self.MainStatusLabel.setGeometry(QtCore.QRect(130, 236, 41, 41))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MainStatusLabel.setFont(font)
        self.MainStatusLabel.setStyleSheet("QLabel{\n"
"    background-color: #c93c3c;\n"
"    border: #c2c2c2;\n"
"    border-radius: 20px;\n"
"    min-height: 27px;\n"
"    color: #ffffff;\n"
"    }\n"
"QLabel:hover{\n"
"    background-color: #b33434;\n"
"    border: #31858f;\n"
"    color: #ffffff;\n"
"    }")
        self.MainStatusLabel.setText("—")
        self.MainStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MainStatusLabel.setObjectName("MainStatusLabel")
        self.NewStatusLabel = QtWidgets.QLabel(Dialog)
        self.NewStatusLabel.setGeometry(QtCore.QRect(480, 236, 41, 41))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.NewStatusLabel.setFont(font)
        self.NewStatusLabel.setStyleSheet("QLabel{\n"
"    background-color: #c93c3c;\n"
"    border: #c2c2c2;\n"
"    border-radius: 20px;\n"
"    min-height: 27px;\n"
"    color: #ffffff;\n"
"    }\n"
"QLabel:hover{\n"
"    background-color: #b33434;\n"
"    border: #31858f;\n"
"    color: #ffffff;\n"
"    }")
        self.NewStatusLabel.setText("—")
        self.NewStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NewStatusLabel.setObjectName("NewStatusLabel")
        self.AcceptButton = QtWidgets.QPushButton(Dialog)
        self.AcceptButton.setGeometry(QtCore.QRect(220, 320, 211, 31))
        font = QtGui.QFont()
        font.setFamily("KB Astrolyte")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.AcceptButton.setFont(font)
        self.AcceptButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(31, 37, 51, 50);\n"
"    border: 2px solid #ffffff;\n"
"    border-radius: 15px;\n"
"    color: #ffffff;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgba(100, 100, 100, 50);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgba(194, 194, 194, 50);\n"
"    border: #c2c2c2;\n"
"    }")
        self.AcceptButton.setObjectName("AcceptButton")
        self.update_logo = QtWidgets.QLabel(Dialog)
        self.update_logo.setGeometry(QtCore.QRect(550, 30, 61, 51))
        self.update_logo.setStyleSheet("background-color: none;\n"
"image: url(:/icons/icons/update.png);")
        self.update_logo.setText("")
        self.update_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.update_logo.setObjectName("update_logo")
        self.BackgroundFrame.raise_()
        self.UpdateTranslationLabel.raise_()
        self.BottomShadowFrame.raise_()
        self.WindowMoveButton.raise_()
        self.ReferenceButton.raise_()
        self.ExitButton.raise_()
        self.MainTitleLabel.raise_()
        self.NewTitleLabel.raise_()
        self.ChooseNewFileButton.raise_()
        self.ChooseMainFileButton.raise_()
        self.MainStatusLabel.raise_()
        self.NewStatusLabel.raise_()
        self.AcceptButton.raise_()
        self.update_logo.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Обновление перевода"))
        self.UpdateTranslationLabel.setText(_translate("Dialog", "Обновить перевод"))
        self.MainTitleLabel.setText(_translate("Dialog", "Основной файл"))
        self.NewTitleLabel.setText(_translate("Dialog", "Дополнительный файл"))
        self.ChooseNewFileButton.setText(_translate("Dialog", "Выбрать"))
        self.ChooseMainFileButton.setText(_translate("Dialog", "Выбрать"))
        self.AcceptButton.setText(_translate("Dialog", "Подтвердить"))
